[package]
name = "tokio-hyper"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
tarantool = { version = "1.1.0", features = ["all", "net_box", "network_client"]}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = "*"
http-body-util = "0.1.0-rc.2"
env_logger = "*"
bytes = "*"
serde = "*"
serde_json = "*"

[lib]
test = false
crate-type = ["cdylib"]
